import getpass
import colorama
from colorama import Fore
import discord
from discord.ext import commands
import os
import getpass
client = commands.Bot(command_prefix=commands.when_mentioned_or("$"))

os.system(f'cls & mode 85,20 & title PHAZIFY AUTOPRESSER')
user = input("Name: ")
print(f'''{Fore.GREEN}
 _    __   __    __   ______   ________  ______  ________  __      __ 
|       \ |  \  |  \ /      \ |        \|      \|        \|  \    /  |
| $$$$$$$\| $$  | $$|  $$$$$$\ \$$$$$$$$ \$$$$$$| $$$$$$$$ \$$\  /  $$
| $$__/ $$| $$__| $$| $$__| $$    /  $$   | $$  | $$__      \$$\/  $$ 
| $$    $$| $$    $$| $$    $$   /  $$    | $$  | $$  \      \$$  $$  
| $$$$$$$ | $$$$$$$$| $$$$$$$$  /  $$     | $$  | $$$$$       \$$$$   
| $$      | $$  | $$| $$  | $$ /  $$___  _| $$_ | $$          | $$    
| $$      | $$  | $$| $$  | $$|  $$    \|   $$ \| $$          | $$    
 \$$       \$$   \$$ \$$   \$$ \$$$$$$$$ \$$$$$$ \$$           \$$    
             ___________LOGGED IN AS: {user}___________                                             
                       88X X PHAZIFY MADE THIS
                                                                                    
        ''' + Fore.GREEN)

token = input("Enter token: ")
sex = input("Keyword: ")
print("READY TO RAPE BLACKS")
###### CODEZZZZZ#######
@client.event
async def on_message(message):
    channel = message.channel
    print("BITCH GOT RAPED:",message.content)
    if message.content.endswith(sex):

        await message.channel.send('#WHITEPOWER4LIFE #KILL ALL NIGGERS #KKK RUNS YOU')
        await message.channel.send('https://cdn.discordapp.com/attachments/939175524910108764/980158676583190548/ezgif-2-844eb02107.gif')
        await message.channel.send('#ANTIJEWISH #REVIVE THE NAZI')
        await message.channel.send('https://media.discordapp.net/attachments/928989534300024883/941814400556335154/image1.gif')
        await message.channel.send('ISIS THE TERRORISTIC ISLAMTIC IMMIGRANT GROUP')
        await message.channel.send('https://tenor.com/view/run-forest-arab-running-man-run-running-away-gif-16278249')
        await message.channel.send('U JEWISH FUCK PASS ME YOUR HEAD')
        await message.channel.send('https://media.discordapp.net/attachments/956679382653624320/961602117691379772/meme-1-1-1.gif')
        await message.channel.send('U WERE SURROUNDED BY 5 WITCHES AND THEY CURSED YOU WITH THE AVADA  KEDAVRA')
        await message.channel.send('STAR6ET & PERK ON TOP OF YOUR MOMS FAT JUICY OILY MASSIVE IMMACULATE ASS')
        await message.channel.send('GET UR NERD GLASSES ON')
        await message.channel.send('LOLOLOLOOLOLLOLOLOLOLOLOLO')
        await message.channel.send('OLOLOLOLLOLOLOLLOLOLOLLOLO')
        await message.channel.send('A BBC WAS GLUED INSIDE OF YOUR MOMS TIGHT PUSSY')
        await message.channel.send('BEG YOUR FRIENDS TO ACC HOP YOU AINT LASTING')
        await message.channel.send('MORON ASS NIGGA GO JERK OFF ON HENTAI PORN')
        await message.channel.send('HOLY SHIT YOU CANT TAKE THE PRESSURE')
        await message.channel.send('PACK BACK NIGGA STAR6ET & PERK ON YOUR GAY ASS')
        await message.channel.send('UR SOUL GETTING SNATCHED LOLOOOOLOL')
        await message.channel.send('U CANT BE COMPARED TO A DEMON')
        await message.channel.send('ILL HEAD SLAP YOU WITH A FROZEN BUTTERSOCK')
        await message.channel.send('UR MOM CAUSED A NATURAL DISASTER WITH HER NASTY PUSSY SMELLING ASS')
        await message.channel.send('KIM JONG UN IS FINNA NUKE THE FUCK OUTTA YOUR DUMB ASS')
        await message.channel.send('GAY ASS NIGGER')
        await message.channel.send('LOL YOU LIKE FUCKING TRANNIES')
        await message.channel.send('WEIRD ASS NIGGA HOP OFF THAT DICK AND COME DIE')
        await message.channel.send('GO JERK OFF TO A TRANNY AND THEN PACK ME SON')
        await message.channel.send('KEEP UP SON U TRIPPED OVER YOUR OWN LEGS??')
        await message.channel.send('UR MY GOON NOW LMFAO')
        await message.channel.send('SELL YOUR TEETHS AT THE TOOTHFAIR BROKE SHIT')
        await message.channel.send('UR MOM BOUGHT U SOME REP JORDANS BROKE NIGGA')
        await message.channel.send('WANT ME TO TAME YOU? SON')
        await message.channel.send('BACK INSIDE THE CAGE YOU GORILLA')
        await message.channel.send('UR MY DOG ON THE LEASH')
        await message.channel.send('YOUR MOM SMASHED YOUR BRAINS OUT')
        await message.channel.send('OLOOLOOOL UR MOMS OILED ASS IS THICK ASF')
        await message.channel.send('I OWN YOUR NASTY DISGRACEFUL INSUFFERABLE ASS')
        await message.channel.send('SAY CHEESE 📷📷📷📷📷📷📷📷📷📷📷📷')
        await message.channel.send('RUN MY SHIT BACKWARDS SEED')
        await message.channel.send('GO PLAY POKEMON GO TRANNY FUCK')
        await message.channel.send('LOLOLOLOL I DOMINATED YOUR MOMMY IN BED')
        await message.channel.send('BOB THE BUILDER COULDNT FIX YOUR NASTY UNFIXABLE ASS')
        await message.channel.send('ILL TEAR APART YOUR MOMS LABIES WEAK FUCK')
        await message.channel.send('YOUR ASS GOT HIGH ON GFUEL????😭😭😭')
        await message.channel.send('UR MOM WAS DOING BACKFLIPS ON THE KITCHENTABLE')
        await message.channel.send('UR MOM WAS A CANDIDATE IN GLORY HOLE')
        await message.channel.send('UR MOM HAS CINEMA GLASSES ON')
        await message.channel.send('UR ASS WAS ON A GORE VIDEO')
        await message.channel.send('BREATH IN AND OUT DONT GET A SEIZURE FAGGOT')
        await message.channel.send('GET YOUR BALLS DROPPED THEN PACK BACK')
        await message.channel.send('UR MY SLAVE LOLOL')
        await message.channel.send('I PUT A SLAVE BURN ON YOUR CHEST')
        await message.channel.send('WORK ON MY PLANTATION BLACK FUCK')
        await message.channel.send('STOP BEATBOXING WITH YOUR MOMS VOICEBOX')
        await message.channel.send('STAY ON')
        await message.channel.send('https://tenor.com/view/packed-too-cool-for-school-ohma-phankiet12-gif-22568352')
        await message.channel.send('GOOFY ASS NIGGA')
        await message.channel.send('LAME ASS BOY')
        await message.channel.send('YOUR MOM IS DIAGNOSED WITH BREAST CANCER')
        await message.channel.send('I HAVE DOMINANCE OVER YOUR ENTIRE FAMILY TREE')
        await message.channel.send('U SUCK')
        await message.channel.send('YOUR BUILT LIKE A STRAW')
        await message.channel.send('WEAK TRANNY BITCH EYES OPEN UR FATHER BOUTTA CREAM IN YOUR FACE')
        await message.channel.send('DID U GET ENOUGH SLEEP??')
        await message.channel.send('RUN MY CHATMOVING HOURS FOR 20 LIGHTYEARS')
        await message.channel.send('PRINGLE ASS BOY')
        await message.channel.send('ORDER SOME LE DRAGON EXPRESS')
        await message.channel.send('UR MOM TRIED CURING HER STAGE 4 CANCER WITH A MIX OF CUM & BLACK DICK')
        await message.channel.send('U SUCK ON YOUR MOMS MODLY TOENAILS')
        await message.channel.send('ILL TRANSFER A COMPUTER VIRUS INSIDE UR MOM')
        await message.channel.send('YOU WILL RUN A MARATHON WITH ME')
        await message.channel.send('STAY HYDRATED YOURE GONNA NEED THAT FAGGOT')
        await message.channel.send('GET UR PILLOW RDY FAGGOT')
        await message.channel.send('U BLACK EBOLA EPEDEMIC AIDS LOOKING SHIT')
        await message.channel.send('LMAOOOOOO CANT FOCUS AND PRESSURE BACK??')
        await message.channel.send('LOOOOL GET BACK ON NICKELODEON YOU LITTLE KID')
        await message.channel.send('OVERWEIGHT BITCH LMAOO YOU GOT OBESITY')
        await message.channel.send('YOUR MOM IS A PROFESSIONAL PORNSTAR LMAOO')
        await message.channel.send('UR MOM GOT ORGY FUCKED BY THE TEENAGE MUTANT NINJA TURTLES')
        await message.channel.send('UR DAD WENT TO THE BARBER AND ASKED IF THEY DO PUBES')
        await message.channel.send('I BACKSLAPPED UR MOTHER WITH A ELECTRIC FLY SWATTER')
        await message.channel.send('UR MOM GAVE BIRTH TO A ALBINO')
        await message.channel.send('I FUCKED UR MOTHER SO ROUGHLY SHES PARALYSED FOR HER ENTIRE LIFE')
        await message.channel.send('FUCK UP')
        await message.channel.send('INSIDE THE COFFIN MORON')
        await message.channel.send('YOU GHETTO RETARD')
        await message.channel.send('UR COUSIN SWALLOWED METH AND PASSED AWAY')
        await message.channel.send('U WERE HAVING LUCID DREAMS OF HAVING SEX WITH ASH KASH')
        await message.channel.send('LOOOOLOOOOL GO BACK TO THE ADOPTION CENTRE')
        await message.channel.send('UR GRANDMOTHER WAS ON A CHEELCHAIR AT THE SIDE OF THE ROAD AT 4 AM')
        await message.channel.send('UR SISTER GOT DOPPED IN THE CHURCH')
        await message.channel.send('UR MOM GOT FUCKED WITH HER HEAD IN A HAPPYMEAL')
        await message.channel.send('UR AUNT IS A SEXWORKER')
        await message.channel.send('HEAD UP')
        await message.channel.send('CHIN UP')
        await message.channel.send('EYES UP')
        await message.channel.send('UR MOM GOT RAILED BY A FUCK MACHINE')
        await message.channel.send('UR STEPBROTHER GOT PUT ON THE CROSS')
        await message.channel.send('LOOOLOOOL YO GRAND GRANDFATHER GOT EXECUTED')
        await message.channel.send('UR ASS BUILT LIKE A SANTA ELF')
        await message.channel.send('HOP INSIDE THE BODYBAG')
        await message.channel.send('NO ONE WILL VISIT YOUR FUNERAL LOOOOL')
        await message.channel.send('UNLOVED UNWANTED FAGGOT LMFAOOO')
        await message.channel.send('LMAAOO I VIBRATED THROUGH UR MOMS CHEST AND RIPPED HER HEART OFF')
        await message.channel.send('UR MOM USED BLACK MAGIC ON YOU LMFAOO')
        await message.channel.send('CLOWN ASS NIGGA GO TO THE CIRCUS')
        await message.channel.send('USE SOME VASELINE FAGGOT')
        await message.channel.send('MICKEY MOUSE LOOKING ASS UR BIG ASS EARS SON')
        await message.channel.send('JERK OFF ON A MANNEQUIN BITCH')
        await message.channel.send('DESPERATE ASS NIGGA GET A BARBIE')
        await message.channel.send('DISCORD HERO LMAO FOCUS')
        await message.channel.send('HOP BACK IN FORTNITE SON')
        await message.channel.send('YOUR NOT HAS DEMENTIA LOLOLOLOLOLOL')
        await message.channel.send('GET YO SHIT SLIPPED L')
        await message.channel.send('MR KRABS SLIPPED OFF YO DICK LOOOOL')
        await message.channel.send('🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀🦀')
        await message.channel.send('GET YO FAT DIABETES FAT ASS OUTTA HERE')
        await message.channel.send('LOLO')
        await message.channel.send('OLO')
        await message.channel.send('LO')
        await message.channel.send('LOOLOO')
        await message.channel.send('OLOL')
        await message.channel.send('LOLO')
        await message.channel.send('LOLOLOL')
        await message.channel.send('FALL OFF THE MOUNT EVEREST THEN PACK ME')
        await message.channel.send('YO SIS GOT KIPNAPPED BY SOME PREDATOR')
        await message.channel.send('FUCK UP CONTINUE UPLOADING CHILD PORNGRAPHY')
        await message.channel.send('STFU EL CHAPO LOOKING ASS')
        await message.channel.send('GET YO DICK SUCKED BY PENNY WISE')
        await message.channel.send('WANT ME TO CLIP YOU?')
        await message.channel.send('BETTER START FOCUSING')
        await message.channel.send('WONT TAKE LONG BEFORE YOU BELONG TO ME')
        await message.channel.send('WIN ME AND TAKE THE TROPHY')
        await message.channel.send('YO NASTY ASS UP UR MY JUNIOR')
        await message.channel.send('GAYLORDIAN LOOKING ASS')
        await message.channel.send('YO MOM OWNS CUM EMPIRE FAGGOT LMAOO')
        await message.channel.send('MAN GOT DROWNED WITH SAND IN HIS MOUTH')
        await message.channel.send('U FUCKING CANNIBAL LOOOL EAT YO OWN DICK')
        await message.channel.send('TURN AROUND AND OBEY ME ON YOUR KNEES')
        await message.channel.send('FATHER IS HERE')
        await message.channel.send('REPENT YOURSELF FAGGOT')
        await message.channel.send('SURRENDER YOU CANT OUTLAST ME LMAO')
        await message.channel.send('WEAK MUTUALS LOLOLOLOLO')
        await message.channel.send('WHATCHU FINNA DO SLAP ME W A TISSUE')
        await message.channel.send('PHAZIFY OWNS YOU LOOL')
        await message.channel.send('I OWN YOU FAGGOT')
        await message.channel.send('TRY XRAY VISION WEAK FUCK')
        await message.channel.send('ASSASSIN WANNA BE LOOOOLLOOOL TROLL')
        await message.channel.send('HOPE YOU CHOKE ON MUSTARD GASS RETARD')
        await message.channel.send('OBEY YOUR MAJESTY')
        await message.channel.send('SUCK UR DADS ORIGAMI DICK NASTY BITCH')
        await message.channel.send('MONKEYGO SWING FROM TREE TO TREE')
        await message.channel.send('WHEN YO MOM FARTS IT SOUNDS LIKE A MK14 LOLOOL')
        await message.channel.send('LOOOLOOOLLOOOLL RATIO + BOZO + L')
        await message.channel.send('DONKEY KONG FUCKED YO MOM LMAOAOOA')
        await message.channel.send('LOUD MIC ME ON YOUR CHROMEBOOK LMAOOOO')
        await message.channel.send('LOOOLOOOL FOCUS UP YOU NERD ASS')
        await message.channel.send('UR AUNT AND UR NOT ARE THOTS LOOOL')
        await message.channel.send('UR SOUL GOT SUCKED OUT BY A VAMPIRE')
        await message.channel.send('LOOOL U BUSTED NUTS ON A UNICORN🦄🦄🦄')
        await message.channel.send('SECRET DOWNSYNDROME MONSTER FROM GRAVITY FALLS')
        await message.channel.send('U THOUGHT U HAD SEX BUT IT WAS IN VRCHAT')
        await message.channel.send('LAME ASS NIGGA SITS 24/7 ON CORD AND CANT LAST')
        await message.channel.send('LISTEN TO XXXTENTACION SAD DEPRESSED FUCK')
        await message.channel.send('TRYNA EGO ME? LAST 100 HOURS FAGGOT')
        await message.channel.send('GET YOUR ⚰️ READY UR GONNA GO 😴')
        await message.channel.send('REST IN PIZZ RETARDED BOZO')
        await message.channel.send('HOP ON FLEX WITH YOUR FAKE GUCCI BELT LOOOL')
        await message.channel.send('THIS BLACK NATURO TALKING SHIT????')
        await message.channel.send('NIGGA HAPPY HE WON NINJA IN A BUILD FIGHT')
        await message.channel.send('YOU LOOK LIKE A DARK SKIN LO KUNG FROM WAKANDA')
        await message.channel.send('U THOUGHT U WAS JESUS WALKING OVER WATER??')
        await message.channel.send('YOU WILL BE CREMATED AFTER ILL KILL YOU')
        await message.channel.send('PROFESSIONAL LASER TAG PLAYER LOOOL')
        await message.channel.send('HOP OFF THE DICK AND LAST WITH ME ALONE')
        await message.channel.send('CORNY ASS NIGGA')
        
client.run(token, bot=False)
